ClaimsAuth/Areas/Product/Controllers/ProductTypeController.cs
using System;
using System.Web.Mvc;
using ClaimsAuth.Infrastructure.Identity;


namespace ClaimsAuth.Areas.Product.Controllers
{
    [ClaimsGroup(ClaimResources.ProductType)]
    public class ProductTypeController : Controller
    {
        [ClaimsAction(ClaimsActions.Index)]
        public ActionResult Index()
        {
            return View();
        }


        [ClaimsAction(ClaimsActions.Create)]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ClaimsAction(ClaimsActions.Create)]
        public ActionResult Create(String id)
        {
            ViewBag.Id = id;
            return View();
        }


        [ClaimsAction(ClaimsActions.View)]
        public ActionResult Edit()
        {
            return View();
        }


        [HttpPost]
        [ClaimsAction(ClaimsActions.Edit)]
        public ActionResult Edit(String id)
        {
            ViewBag.Id = id;
            return View();
        }
    }
}

ClaimsAuth/Controllers/HomeController.cs
using System.Security.Claims;
using System.Web.Mvc;

namespace ClaimsAuth.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult AddNonPersistedClaim()
        {
            var identity = (ClaimsIdentity)ClaimsPrincipal.Current.Identity;
            identity.AddClaim(new Claim("Hello", "Non Persisted Identity"));

            return RedirectToAction("Index", "Profiler");
        }
    }
}

ClaimsAuth/Controllers/SecretController.cs
using System.Web.Mvc;
using ClaimsAuth.Infrastructure.Identity;


namespace ClaimsAuth.Controllers
{
    [ClaimsGroup(ClaimResources.Secrets)]
    public class SecretController : Controller
    {
        [ClaimsAction(ClaimsActions.Index)]
        public ActionResult Index()
        {
            return View();
        }


        [ClaimsAction(ClaimsActions.Create)]
        [ClaimsAction(ClaimsActions.Index)]
        public ActionResult CreateSomething()
        {
            return View();
        }


        [ClaimsAction(ClaimsActions.Delete)]
        public ActionResult EditMagicBeans()
        {
            return View();
        }
    }
}

ClaimsAuth/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Basic Index</h2>
        <p>
            @Html.ActionLink("Basic Index", "Index", "Secret")
        </p>
    </div>
    <div class="col-md-4">
        <h2>Create Something</h2>
        <p>
            @Html.ActionLink("Basic Index", "CreateSomething", "Secret")
        </p>
    </div>
    <div class="col-md-4">
        <h2>Magic Beans</h2>
        <p>
            @Html.ActionLink("Magic Beans", "EditMagicBeans", "Secret")
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Product type</h2>
        <ul>
            <li>@Html.ActionLink("Index", "Index", "ProductType", new { area = "Product" }, null)</li>
            <li>@Html.ActionLink("Create", "Create", "ProductType", new { area = "Product" }, null)</li>
            <li>@Html.ActionLink("Edit", "Edit", "ProductType", new { area = "Product" }, null)</li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>Products</h2>
        <ul>
            <li>@Html.ActionLink("Index", "Index", "Product", new { area = "Product" }, null)</li>
            <li>@Html.ActionLink("Create", "Create", "Product", new { area = "Product" }, null)</li>
            <li>@Html.ActionLink("Edit", "Edit", "Product", new { area = "Product" }, null)</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Authorized</h2>
        <ul>
            <li>@Html.ActionLink("Authenticated", "Index", "Authenticated")</li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>Experiments</h2>
        <ul>
            <li>@Html.ActionLink("Add Non-Persisted Claim", "AddNonPersistedClaim")</li>
        </ul>
    </div>
</div>

ClaimsAuth/Views/Home/PasswordValidation.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>